# Generated by Django 4.1.5 on 2023-01-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEspaco', models.CharField(max_length=100, verbose_name='nomeEspaco')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeModalidade', models.CharField(max_length=100, verbose_name='nomeModalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100, verbose_name='nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateField(auto_now=True, verbose_name='data_hora_inicio')),
                ('data_hora_fim', models.DateField(auto_now=True, verbose_name='data_hora_fim')),
                ('responsavel', models.CharField(max_length=100, verbose_name='responsavel')),
                ('limite', models.IntegerField(verbose_name='limite')),
                ('turma', models.CharField(max_length=100, verbose_name='turma')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.espaco')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modalidades')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nivel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
        ),
    ]
