# Generated by Django 4.1.5 on 2023-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espaco',
            name='nomeEspaco',
        ),
        migrations.RemoveField(
            model_name='modalidades',
            name='nomeModalidade',
        ),
        migrations.AddField(
            model_name='espaco',
            name='nome_espaco',
            field=models.CharField(default='Ginasio', max_length=100, verbose_name='NomeEspaco'),
        ),
        migrations.AddField(
            model_name='modalidades',
            name='nome_modalidade',
            field=models.CharField(default='Modalidade', max_length=100, verbose_name='NomeModalidade'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='nivel',
            field=models.CharField(default='Nivel', max_length=100, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='status', max_length=100, verbose_name='Status'),
        ),
    ]
