# Generated by Django 4.1.5 on 2023-01-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_espaco_nomeespaco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=20, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('senha', models.CharField(max_length=30, verbose_name='Senha')),
            ],
        ),
    ]
