# Generated by Django 4.1.5 on 2023-02-03 00:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100, verbose_name='Nome')),
                ('turma', models.IntegerField(default='', verbose_name='Ano')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='data_hora_fim',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='data_hora_inicio',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='limite',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='espaco',
            name='nome_espaco',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_fim',
            field=models.DateTimeField(default='', verbose_name='Data e hora do Fim'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_inicio',
            field=models.DateTimeField(default='', verbose_name='Data e hora de Início'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='quantidade_limite',
            field=models.IntegerField(default='', verbose_name='Quantidade e Limite'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='espaco',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='status',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default='', verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(default='', max_length=14, unique=True, verbose_name='Matricula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='', max_length=10, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='aaa', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='admin', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='espaco',
            field=models.ForeignKey(default='espaco', on_delete=django.db.models.deletion.CASCADE, to='core.espaco'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nivel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.nivel'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='modalidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.modalidade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='turma',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.turma'),
        ),
        migrations.DeleteModel(
            name='Modalidades',
        ),
    ]
