# Generated by Django 4.1.5 on 2023-02-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='data_fim',
            field=models.CharField(default='a', max_length=20, verbose_name='Data e hora do Fim'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_inicio',
            field=models.CharField(default='a', max_length=20, verbose_name='Data e hora de Início'),
        ),
    ]
