# Generated by Django 4.1.5 on 2023-02-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_atividade_modalidade_alter_atividade_nivel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
